{ name = "triphut-dao-offchain"
, dependencies =
  [ "aeson"
  , "aff"
  , "aff-promise"
  , "arraybuffer"
  , "arraybuffer-types"
  , "arrays"
  , "b64"
  , "cardano-plutus-data-schema"
  , "cardano-transaction-lib"
  , "cardano-types"
  , "control"
  , "datetime"
  , "effect"
  , "either"
  , "encoding"
  , "exceptions"
  , "foldable-traversable"
  , "foreign"
  , "foreign-object"
  , "functions"
  , "gen"
  , "js-bigints"
  , "maybe"
  , "monad-logger"
  , "mote"
  , "newtype"
  , "node-buffer"
  , "node-fs"
  , "ordered-collections"
  , "partial"
  , "plutus-types"
  , "posix-types"
  , "prelude"
  , "quickcheck"
  , "quickcheck-utf8"
  , "spec"
  , "strings"
  , "transformers"
  , "tuples"
  , "uint"
  , "unfoldable"
  , "uplc-apply-args"
  ]
, packages = ./packages.dhall
, sources =
  [ "src/**/*.purs"
  , "exe/**/*.purs"
  , "test/**/*.purs"
  , ".spago/lambda-buffers/v2.0.0/runtimes/purescript/lbr-prelude/src/**/*.purs"
  , ".spago/lambda-buffers/v2.0.0/runtimes/purescript/lbr-plutus/src/**/*.purs"
  , "types/LambdaBuffers/**/*.purs"
  , "types/ScriptArguments/**/*.purs"
  ]
}
