flowchart TD
    A[Initial_UTXO]
    B{Create_Index_Tx}
    A--"` Spends the UTXO referenced in its IndexNftConfig argument`"---B
    B ==>|"`Pays the initial IndexNftDatum and Index NFT to the script`"| E[Index_Validator]